squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs
There was a small typo where `addColumnNull`'s comment referred to `addColumnDefault`.
=> Fixes addColumnNull typo

squeal-postgresql/src/Squeal/PostgreSQL.hs, squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs, squeal-postgresql/src/Squeal/PostgreSQL/Query.hs, squeal-postgresql/src/Squeal/PostgreSQL/Render.hs, squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs
Right now it is possible to create invalid queries by using aliases that has the same name as a table name.
For example, the following query
```
select
( #user ! #name `As` #userName :* Nil)
( from (table (#users `As` #user)) )
```
will render as
```
SELECT user.name AS userName FROM users AS user
```
which is not a valid query as it collides with the built-in user table.
When quoting aliases the query will render as follows
```
SELECT "user"."name" AS "userName" FROM "users" AS "user"
```
which is a valid query.
This change will also make it possible to have table/column names with camel casing, etc. (Without quotes the names are lowercased in postgres)
All the renderQuery, etc tests breaks with this change, let me know if you want to pull this in and I will update the tests.
=> Add double quotes around aliases

RELEASE NOTES.md, squeal-postgresql/squeal-postgresql.cabal, squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs, squeal-postgresql/src/Squeal/PostgreSQL/Query.hs, squeal-postgresql/src/Squeal/PostgreSQL/Render.hs, squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs
Fixes #35 @ChShersh 
WIP
Tricky bits:
1. many functions accept either json or jsonb
2. many functions also overloaded on operand types
3. nullity of many results depends on nullity of either argument; which does not need to be the same
Unimplemented: most of table 9.45 and 9.46 at https://www.postgresql.org/docs/10/static/functions-json.html
=> JSON operator/function support WIP

squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
A fairly simple addition to the available collection of function: the often used `ILIKE` function, which is exactly similar to `LIKE`, but case insensitive.
=> Add the `ilike` function

squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs, squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs
Solution suggested for #71.
This solution is rather redundant with some of the functions that are already available, but I didn't want to risk breaking compability. I would really like to avoid having to resort to the `deleteTarget` but couldn't find a way to avoid it.
Maybe you'll have pointers as to how to improve this.
=> Add support for `DELETE FROM table USING`

squeal-postgresql/exe/Example.hs, squeal-postgresql/src/Squeal/PostgreSQL.hs, squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs, squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs, squeal-postgresql/src/Squeal/PostgreSQL/Query.hs, squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs, squeal-postgresql/src/Squeal/PostgreSQL/Transaction.hs
Introduces a `Selection` type
```Haskell
data Selection db params grp from row where
List
:: SListI row
=> NP (Aliased (Expression db params grp from)) row
-> Selection db params grp from row
Star
:: HasUnique tab from row
=> Selection db params 'Ungrouped from row
DotStar
:: Has tab from row
=> Alias tab
-> Selection db params 'Ungrouped from row
Also
:: Selection db params grp from right
-> Selection db params grp from left
-> Selection db params grp from (Join left right)
```
`Also` appends two `Selection`s, even selections of different forms, by rendering as ", ". It's analogous to `also` which is similar but for `TableExpressions`.
It also removes a lot of boilerplate by using the extant RenderSQL typeclass to abstract and remove various render___ functions. More could possibly be …
=> Add a `Selection` type and more `RenderSQL` instances

squeal-postgresql/exe/Example.hs, squeal-postgresql/src/Squeal/PostgreSQL.hs, squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs, squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs, squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs, squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs, squeal-postgresql/src/Squeal/PostgreSQL/Query.hs, squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs, squeal-postgresql/test/Specs/ExceptionHandling.hs
This PR removes the `DBType` kind in favor of being more explicit about common table expression scoping. It also adds common use case types `Query_` and `Manipulation_` with empty common table expression scope and Haskell types for parameters and return values:
```Haskell
type family Query_ (schemas :: SchemasType) (params :: Type) (row :: Type) where
Query_ schemas params row = Query '[] schemas (TuplePG params) (RowPG row)
type family Manipulation_ (schemas :: SchemasType) (params :: Type) (row :: Type) where
Manipulation_ schemas params row = Manipulation '[] schemas (TuplePG params) (RowPG row)
```
=> Add `Query_` and `Manipulation_` type families

squeal-postgresql/exe/Example.hs, squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs, squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs, squeal-postgresql/src/Squeal/PostgreSQL/Render.hs, squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs, squeal-postgresql/test/Specs/ExceptionHandling.hs
This PR should hopefully address #87 indirectly. It introduces `VarArray` and `FixArray` newtypes, removes the `ToArray` typeclass and adds a `ToFixArray` type class. Additionally, nesting behavior is treated differently so that `'PGfixarray` now takes a list of `Nat`s to express a multidimensional array, while variable length arrays should be unnested.
=> Array refactor

squeal-postgresql/exe/Example.hs, squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs, squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs, squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs, squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
* Resolves #86 by adding a new `outer` scope variable and `exists`.
* Takes some ideas from #74 and simplifies subqueries
* `in_` just takes a list
* `notIn` added
* `subAll`/`subAny` unifies the rest
* removes row constructor subqueries (we can add them back later if anyone needs them)
=> Subqueries

squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs, squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs
Proposal to start implementing #57.
I have tried many - clearly overengineered - other solutions but I think I've taken too much time on a feature that we should really add to Squeal, so here's a simpler, more down-to-earth implementation. It lets you migrate up, down and display everything.
- Migrate one up or migrate X up could be implemented by modifying the `migrateUp` signature and taking an optional counter. Not the prettiest solution possible, but probably the easiest way to implement this. Same for migrate down.
- The `optparse-generic` is a _suggestion_, but I'm ready to change it. @echatav, I know you found it was a heavy dependency to add. I first tried my hand with `getopt-generics` as you suggested, but it doesn't support sum type. I can rewrite the parser using it to fetch a …
=> Add default main utility for migrations

README.md, squeal-postgresql/exe/Example.hs, squeal-postgresql/squeal-postgresql.cabal, squeal-postgresql/src/Squeal/PostgreSQL.hs, squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs, squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs, squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs, squeal-postgresql/src/Squeal/PostgreSQL/Pool.hs, squeal-postgresql/src/Squeal/PostgreSQL/Render.hs, squeal-postgresql/src/Squeal/PostgreSQL/Transaction.hs, squeal-postgresql/test/Specs/ExceptionHandling.hs, stack.yaml
Resolves #109 
This is my attempt to move away from `MonadBaseControl` to `MonadUnliftIO`. Let me know what do you think! What can be done further:
1. Add `MonadUnliftIO` instance for `PoolPQ`
2. Replace all usages of `MonadBase IO` with `MonadIO` (because they are essentially the same thing but `MonadIO` is much simpler).
I didn't remove helper functions that can help to create `MonadBaseControl` instances in order to simplify migration for the existing users.
=> [#109] Move from MonadBaseControl to MonadUnliftIO

squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs, squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs, squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs, squeal-postgresql/test/Specs/ExceptionHandling.hs
* Change the signatures of `migrateUp` and `migrateDown` to be more interoperable with sessions
* Remain compatible with Squeal 0.4 by putting the `schema_migrations` table back in the `public` schema.
* Add doctests for `defaultMain`
* Enable both pure and impure migrations with `Migratory` typeclass and `Terminally` newtype.
=> Simplify migration signatures

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Subquery.hs
Tiny doc fix: the `subAny` doctest was the same as `subAll`. (BTW, I _love_ what you did with the whole subquery module).
=> Fix example code for subAny

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Aggregate.hs, squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
I suspect this is a typo, but in case this requires some justification, here's an exceprt from [PostgreSQL documentation](https://www.postgresql.org/docs/11/functions-aggregate.html) - emphasis is mine :
> It should be noted that except for count, these functions return a null value when no rows are selected. **In particular, sum of no rows returns null, not zero as one might expect**, and array_agg returns null rather than an empty array when there are no input rows. The coalesce function can be used to substitute zero or an empty array for null when necessary.
So the `sum` aggregate should not return a `null` column - over aggregates seem to have the proper return, but sum did not. This PR fixes this.
__Edit__: fixed tests broken by the signature change. I opted for a simple COALESCE - …
=> Make `sum` aggregate returns a nullable value

squeal-postgresql/squeal-postgresql.cabal, squeal-postgresql/src/Squeal/PostgreSQL.hs, squeal-postgresql/src/Squeal/PostgreSQL/Pool.hs, squeal-postgresql/test/Specs/ExceptionHandling.hs
Previously connection pools were handled by defining a `PoolPQ` monad with a `MonadPQ` instance. Turns out this was sort of dumb. What it did was run each query by taking a connection from the pool, running the query, and then returning the connection to the pool. This is _not_ what is usually expected in a real use case. In a real use case, like a web service, you probably want to use a single connection to serve an endpoint when it's called. This PR resolves #138.
=> Rewrite of connection pools

squeal-postgresql/src/Squeal/PostgreSQL/List.hs, squeal-postgresql/src/Squeal/PostgreSQL/PG.hs, squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs
This should improve both compilation times and memory usage for large queries and tables.
This is super ugly but seems to work. This works around the way GHC currently handles recursive type families. Basically as far as I know when a type family matches one of the cases, it doesn't actually replace the types, but rather carries around the proofs, which consumes memory and makes things slower. What this PR should do is remove the amount and depth of carrying GHC should do.
I didn't tackle the more complicated type families yet.
Couldn't test actual performance since I don't have a large enough project using the latest version of squeal.
This whole thing could probably be done with TH, but I'm not familiar enough with it.
This might help with #28
@Raveline it would be great if you could …
=> Unrolled some type families

squeal-postgresql/benchmarks/Main.hs, squeal-postgresql/benchmarks/README.md, squeal-postgresql/benchmarks/lib/Queries.hs, squeal-postgresql/benchmarks/lib/Schema.hs, squeal-postgresql/squeal-postgresql.cabal
Based on the brief discussion [here](https://github.com/morphismtech/squeal/issues/158) I built up a skeleton for microbenchmarking query rendering. As it is, it's probably not useful but meant to act as a foundation to build a real benchmark suite on.
Run via `stack bench`.
What I don't understand is how the query actually gets composed with its params when running `manipulateParams_ ...`.
There's lots of extra noise here, mostly because I wrote some facilities to auto-generate manipulations with different params based on the data types.
The idea was to facilitate benchmarking queries rendered with auto-generated parameters. I mean benchmarking building up the full `ByteString` that actually gets sent to Postgres.
I don't expect this to be merged, I just want to know if I'm heading down …
=> Added a skeleton benchmark suite + mockup queries

.circleci/config.yml, squeal-postgresql/benchmarks/Main.hs, squeal-postgresql/benchmarks/lib/DBHelpers.hs, squeal-postgresql/benchmarks/lib/DBSetup.hs, squeal-postgresql/benchmarks/lib/Queries.hs, squeal-postgresql/benchmarks/lib/Schema.hs, squeal-postgresql/squeal-postgresql.cabal
This PR adds benchmarks running against an actual database.
So far `INSERT` manipulations are only tested, but the skeleton can be used to facilitate any queries.
Other changes:
* Swapped `criterion` in favor of `gauge` for a much lighter dependency footprint
* Cleaned up Schema a bit
* Added a composite type as requested (not benchmarked yet)
Again, the bench folder contains a lot of noise, mostly functionality for building up other benchmark groups.
If this qualifies for a merge, may I suggest adding `stack bench` a part of the CI pipeline? I've never used CircleCI so I don't want to go around messing with it, but a separate job for benchmarks would help us keep an eye on performance regressions.
=> Added benchmarks for DB queries

squeal-postgresql/squeal-postgresql.cabal, squeal-postgresql/src/Squeal/PostgreSQL/Session.hs
The purpose of this PR is to add an instance of `MonadBaseControl` to the PQ monad. In doing so, I also had to add a `MonadBase` instance, and a helpful type alias.
This PR also required two new dependencies, [`monad-control`](https://www.stackage.org/lts-14.12/package/monad-control-1.0.2.3), and [`transformer-base`](https://www.stackage.org/lts-14.12/package/transformers-base-0.4.5.2). The versions added are available for all all three stack-lts-x.yml files listed in the root directory of the project.
=> PQ instances for MonadBase and MonadBaseControl

squeal-postgresql/squeal-postgresql.cabal, squeal-postgresql/src/Squeal/PostgreSQL/Session.hs
This PR adds in three new instances for the `PQ` monad, `MonadCatch`, `MonadThrow`, and `MonadMask`. 
Additionally, I've added a dependency on the hackage library [exceptions](https://hackage.haskell.org/package/exceptions-0.10.4/docs/Control-Monad-Catch.html) which defines the typeclasses above mentioned.
Finally, test suite is passing on my local machine.
=> Add in PQ instance for MonadCatch, MonadThrow, and MonadMask

squeal-postgresql/src/Squeal/PostgreSQL/Type/Alias.hs
include the original fields when a `Has` instance is not found
=> provide a more useful error message for Has

squeal-postgresql/src/Squeal/PostgreSQL/Session/Decode.hs, squeal-postgresql/src/Squeal/PostgreSQL/Type/Schema.hs
Sometimes your Haskell enum doesn't exactly match your PG enum so you must hand-roll a decoder. This is a convenient combinator for that.
=> custom enum decoder

squeal-postgresql/bench/Gauge/DBSetup.hs, squeal-postgresql/exe/Example.hs, squeal-postgresql/src/Squeal/PostgreSQL.hs, squeal-postgresql/src/Squeal/PostgreSQL/Definition/Constraint.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Migration.hs
This factors out `ReferentialAction`s from `OnDeleteClause`s and `OnUpdateClauses`s and adds to missing actions `SetNotNull` and `SetDefault`.
=> ReferentialAction

squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs, squeal-postgresql/src/Squeal/PostgreSQL/Query/Select.hs
This change makes it possible to have polymorphic lateral context! When looking up a column heretofore, the relevant typeclasses would search through `Join lat from`. This is the "correct" ordering as far as the structure from left to right in the query, making `lat` consistently ordered as one goes through nested lateral joins or nested subquery expressions. However, it doesn't really matter how the lookup orders the columns. And if the lookup searches through `Join from lat` instead then thanks to good old Haskell lazy list appending, if a query only references columns in `from` then it will work no matter the `lat`. With a small proviso; if you leave `lat` polymorphic, then you _must_ qualify all columns since there _could_ be more than one table even if `from` has only one table in …
=> polymorphic lateral context

squeal-postgresql/src/Squeal/PostgreSQL.hs, squeal-postgresql/src/Squeal/PostgreSQL/Definition/Procedure.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation/Delete.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation/Insert.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation/Update.hs
The table being manipulated in insertInto, update and deleteFrom can be re-aliased and then referenced by its new alias.
=> Make manipulated tables aliasable

squeal-postgresql/exe/Example.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation/Insert.hs, squeal-postgresql/src/Squeal/PostgreSQL/Manipulation/Update.hs
By making the `from` type in `Values`s polymorphic, setting clauses should be sharable between `QueryClause`s and `ConflictClause`s in an `insertInto`.
=> make more things polymorphizable

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Inline.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Decode.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Encode.hs, squeal-postgresql/src/Squeal/PostgreSQL/Type/PG.hs
Instances all do the obvious thing ie delegate to the wrapped type.
=> Add IsPG, ToPG, FromPG, Inline instances for Const, K, Constant

squeal-postgresql/src/Squeal/PostgreSQL/Type/List.hs, squeal-postgresql/src/Squeal/PostgreSQL/Type/Schema.hs
`Sublist` & `SubDB` type families should unlock a new form of type safety. Because any SQL statement which is valid in the scope of a given set of schemas will be valid in the scope of a larger set of schemas, any Squeal code which is typechecked against a `db0 :: SchemasType`, should also work for a `db1` for which `SubDB db0 db1 ~ 'True`.
=> Sublist & SubDB

squeal-postgresql/src/Squeal/PostgreSQL/Query/Table.hs
This is a fix for issue:  #287 and modified `lockRows` to prevent a runtime postgresql error that would happen if you try to add a `LockingClause` to a grouped table expression.
=> update lockRows to Ungrouped table exprs

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Json.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression/Null.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression/Text.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression/Time.hs
Adds a type family to combine nullity of two arguments, and two functions for determining if a string is a substring of another string. 
I've wrote a version `strpos` a few of times while writing application code, and think it'd be a useful addition to `squeal`, as it directly mirrors an existing Postgresql.
=> Add in functions: strpos, CombineNullity

squeal-postgresql-ltree/squeal-postgresql-ltree.cabal, squeal-postgresql-ltree/src/Squeal/PostgreSQL/LTree.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Exception.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Migration.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Oid.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Result.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Transaction.hs
retain `UnliftIO` instance for `PQ` but use `Control.Monad.Catch` instead
=> use Control.Monad.Catch instead of UnliftIO

squeal-postgresql-ltree/src/Squeal/PostgreSQL/LTree.hs
For now, just have a type error and use `inline` instead or cast to `text`. There is a real binary encoding but I couldn't get my tests to pass.
=> type error for binary instances for LTree and friends

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Subquery.hs
these should produce `Condition`s meaning nullable boolean values because e.g. `select NULL in (NULL)` is `NULL`.
=> more correct `in_` and `notIn`

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Composite.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression/Type.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Oid.hs, squeal-postgresql/src/Squeal/PostgreSQL/Type/Schema.hs, squeal-postgresql/test/Property.hs
This PR broadens user defined row types to include table and view row types. Previously Squeal only truly supported composite row types. Collectively, these are known as relations. Other kinds of relations besides composites, tables and views are not yet supported. There are still some iffy corner cases but I think it's an improvement.
=> Expand user types to include tables and views

squeal-postgresql/src/Squeal/PostgreSQL/Type/List.hs
Previously, the sort done for pretty printing used [`If`](https://hackage.haskell.org/package/base-4.16.1.0/docs/Data-Type-Bool.html#t:If). Because of how type families work, this doesn't short circuit like value-level if, and always evaluates both branches, which made sorting very slow and run out of memory with a larger schema like in (credit @wyao-simspace ). Sorting only happens in the case of an error, so this didn't come up in normal testing.
```haskell
type Schema =
'[ "public" ::: SomeTables
] :: Sq.SchemasType
type SomeTables =
'[ "a" ::: 'Sq.Table SomeTable
, "b" ::: 'Sq.Table SomeTable
, "c" ::: 'Sq.Table SomeTable
, "d" ::: 'Sq.Table SomeTable
, "e" ::: 'Sq.Table SomeTable
, "f" ::: 'Sq.Table SomeTable
, "g" ::: 'Sq.Table SomeTable
, "h" ::: 'Sq.Table SomeTable
, "i" ::: …
```
=> Use properly short-circuiting conditional for type-level merge sort

squeal-postgresql/src/Squeal/PostgreSQL/Session/Encode.hs, squeal-postgresql/src/Squeal/PostgreSQL/Type/Schema.hs
Squeal had combinators for hand rolling `FromPG` instances for `PGenum`s and `PGcomposite`s. This PR adds combinators for hand rolling `ToPG` instances. To do this it loosens the `EncodeParams` type to be polykinded `newtype EncodeParams (db :: SchemasType) (tys :: [k]) (x :: Type)`. The type variable `tys` can be a list of any kind, where before it was `[NullType]`. We need to instantiate it for one other list, `RowType`. Then we define the following combinator to use these `RowType`d parameter encodings to define `toPG` methods.
```Haskell
rowParam
:: forall db row x. (PG x ~ 'PGcomposite row, SOP.All (OidOfField db) row)
=> EncodeParams db row x
-> x -> ReaderT (SOP.K LibPQ.Connection db) IO Encoding
```
To construct `RowType`d parameter encodings, we can use some old combinators like …
=> Combinators for hand rolling `ToPG` for `PGenum`s and `PGcomposite`s

squeal-postgresql/exe/Example.hs, squeal-postgresql/squeal-postgresql.cabal, squeal-postgresql/src/Squeal/PostgreSQL/Session.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Monad.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Statement.hs
Introduces new `Prepared` statement type as well as new functions `prepare` and `prepare_` to construct `Prepared` statements in a `MonadPQ`. This generalizes and factors out of `executePrepared` from earlier.
`Prepared` has many instances, notably `Functor`, `Profunctor`, `Traversing`, `Category` and `Arrow`.
The PR also adds `MonadFix`, `Alternative` and `MonadPlus` instances to `PQ`.
=> New `Prepared` statement type and `prepare` functions

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Array.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression/Null.hs, squeal-postgresql/src/Squeal/PostgreSQL/Expression/Range.hs, squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
* Relaxes the nullity of `(.<@)`, `(@>.)`, `arrAll`, and `arrAny`
* Adds a `just_` function which replaces `notNull`
* Deprecates `notNull` because it's a little unclearly named I think
Resolves #315
=> Null functions

squeal-postgresql/src/Squeal/PostgreSQL/Session/Decode.hs
Positionally decode rows into products, either records or tuples. Resolves #330
=> Add a new `genericProductRow` combinator

cabal.project, squeal-postgresql/src/Squeal/PostgreSQL/Session/Monad.hs
A follow on from #335 for `ghc-9.4.5`.
Use a couple of alternate source-repository-package dependencies until records-sop is updated and published to hackage, see https://github.com/kosmikus/records-sop/issues/12.
```
$ cabal build all --enable-tests --enable-benchmarks
Cloning into '/.../dist-newstyle/src/records-s_-cc0a9700f9cd5a00'...
remote: Enumerating objects: 321, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 321 (delta 31), reused 63 (delta 20), pack-reused 234
Receiving objects: 100% (321/321), 61.90 KiB | 2.38 MiB/s, done.
Resolving deltas: 100% (137/137), done.
HEAD is now at db2d052 Bump stackage resolver to lts-20.18 for ghc-9.2.7.
Resolving dependencies...
Build profile: -w ghc-9.4.5 -O1
In order, the …
```
=> For ghc >= 9.4 use a fork of records-sop with relaxed bounds.

squeal-postgresql/src/Squeal/PostgreSQL/Session/Pool.hs
This is the warning:
```
$ cabal repl squeal-postgresql
Build profile: -w ghc-8.6.5 -O1
...
src/Squeal/PostgreSQL/Session/Pool.hs:86:12: warning: [-Wdeprecations]
In the use of ‘createPool’ (imported from Data.Pool):
Deprecated: "Use newPool instead"
|
86 |   liftIO $ createPool (connectdb conninfo) finish stripes idle maxResrc
|    
```
=> As suggested by -Wdeprecations; use newPool instead.

squeal-postgresql/src/Squeal/PostgreSQL/Session.hs
=> [fix] add proper MonadFail instance

.github/workflows/ci.yml
https://github.com/haskell/actions deprecated
replaced with https://github.com/haskell-actions/setup
=> update GitHub Action

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Array.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session.hs, squeal-postgresql/src/Squeal/PostgreSQL/Session/Decode.hs
Array functions and `ArrayField` utility for using overloaded labels together with `runArrayField` and a state computation such as `pgtype` or `rowValue _`.
=> Array utilities
