squeal-postgresql/exe/Example.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs

Table constraints pushed through

Pgconstraint4

---

squeal-postgresql/exe/Example.hs
squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs
stack.yaml

Here we rejigger the constraints system.

Constraints

---

README.md
squeal-postgresql/exe/Example.hs
squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/src/Squeal/PostgreSQL.hs
squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs
squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs
squeal-postgresql/src/Squeal/PostgreSQL/Pool.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
squeal-postgresql/src/Squeal/PostgreSQL/Render.hs
squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs
squeal-postgresql/src/Squeal/PostgreSQL/Transaction.hs

0.3+types3

---

RELEASE NOTES.md
scrap-your-nils.md
squeal-postgresql/exe/Example.hs
squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/src/Squeal/PostgreSQL.hs
squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs

Scrap your Nils

---

squeal-postgresql/src/Squeal/PostgreSQL/Pool.hs

It's taken me more time than I want to admit before understanding how to exactly use `PoolPQ`. I add to look at the source before it finally clicked. So I suggest adding this small dummy example in the documentation. (It's not in doctest because it would require some import and also running migrations, getting to the point where it would be rather unreadable).

Add example use for PoolPQ

---

squeal-presentation-2018-09-12.html

As kindly proposed by @echatav, this is the slides from a presentation I gave to the French start-up Fretlink about Squeal.

Add the 2018-09-12 presentation slides from @Raveline

---

squeal-postgresql/exe/Example.hs
squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/src/Squeal/PostgreSQL.hs
squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs
squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs
squeal-postgresql/src/Squeal/PostgreSQL/Pool.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs
squeal-postgresql/src/Squeal/PostgreSQL/Transaction.hs
squeal-postgresql/test/Specs/ExceptionHandling.hs

multi-schema support

---

squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs

Dev window stats

---

squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs

Dev drop schema

---

squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs

Nested rows

---

squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs

Time operators and functions

---

squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
squeal-postgresql/src/Squeal/PostgreSQL/Render.hs
squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs

Text Search and new Function types

Text Search and new Function types

---

squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs
squeal-postgresql/src/Squeal/PostgreSQL/Transaction.hs

and fix `defaultMode`
resolves #111

retry transactions on serialization failure

---

squeal-postgresql/exe/Example.hs
squeal-postgresql/src/Squeal/PostgreSQL.hs
squeal-postgresql/src/Squeal/PostgreSQL/Alias.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs
squeal-postgresql/test/Specs/ExceptionHandling.hs

simplify column expression

---

squeal-postgresql/src/Squeal/PostgreSQL/Alias.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs

withRecursive

---

squeal-postgresql/exe/Example.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs

Yep! Simple fix for #142 to constrain the alias type variable correctly.

Fix alias type variable in createDomain

---

squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Comparison.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Logic.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/SetOf.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/TextSearch.hs
squeal-postgresql/src/Squeal/PostgreSQL/Schema.hs

Preliminary support for user defined functions and operators

User defined function support

---

squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/src/Squeal/PostgreSQL/List.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/Migration.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs
stack.yaml

Factor out free categories as useful and motivated enough to constitute its own [library](https://github.com/morphismtech/free-categories).

factor out free categories

---

squeal-postgresql/exe/Example.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition.hs

closes #150
Used the new stuff in the example to make sure it works. You can remove not if you find it confusing as an example.
It was tricky to find where to put it to avoid import cycles.

Added hask and PGNullityTyped

---

squeal-postgresql/src/Squeal/PostgreSQL/Query.hs

use final encoding for group by clause

---

squeal-postgresql/src/Squeal/PostgreSQL/Query.hs

polymorphise grouping for select distinct

---

squeal-postgresql/src/Squeal/PostgreSQL/Binary.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Type.hs
squeal-postgresql/src/Squeal/PostgreSQL/PG.hs
squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs
squeal-postgresql/test/Property.hs
squeal-postgresql/test/Spec.hs

parameter  oids

---

squeal-postgresql/src/Squeal/PostgreSQL/Alias.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Null.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs

lateral joins

---

squeal-postgresql/exe/Example.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Parameter.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Type.hs

type inference

---

squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Aggregate.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Array.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Comparison.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Composite.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Json.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Literal.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Logic.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Math.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Null.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Parameter.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Range.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Set.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Sort.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Subquery.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Type.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Window.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation.hs
squeal-postgresql/src/Squeal/PostgreSQL/Query.hs

re-order lateral params and some variable name changes

Lateral fix

---

squeal-postgresql/src/Squeal/PostgreSQL/PQ.hs
squeal-postgresql/src/Squeal/PostgreSQL/PQ/Exception.hs
squeal-postgresql/src/Squeal/PostgreSQL/PQ/Oid.hs
squeal-postgresql/src/Squeal/PostgreSQL/PQ/Result.hs
squeal-postgresql/src/Squeal/PostgreSQL/PQ/Transaction.hs
squeal-postgresql/test/Spec.hs

* pattern UniqueViolation
* pattern CheckViolation
* renaming
* refactoring
* export throwSqueal

exceptions

---

.gitignore
stack.lts-14.12.yaml
stack.lts-14.27.yaml
stack.lts-15.4.yaml
stack.yaml

LTS versions

---

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Subquery.hs

generalize some logic

---

squeal-postgresql/bench/Gauge/DBHelpers.hs
squeal-postgresql/squeal-postgresql.cabal

version 0.6.0.0

---

.gitignore
squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/src/Squeal/PostgreSQL.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition/Comment.hs

Added comments on tables, types, views, indices, and functions. One other thing we could add is comments on individual columns, or unsafe comments, but I didn't feel confident about how to do those things in an ergonomically good way.

Added Comments to Definition

---

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Type.hs

The instance was missing, this adds it.

add missing PGTyped instance for PGinet

---

squeal-postgresql/src/Squeal/PostgreSQL/Session/Decode.hs

instance MonadFail (DecodeRow row) where

---

squeal-postgresql/exe/Example.hs
squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/src/Squeal/PostgreSQL.hs
squeal-postgresql/src/Squeal/PostgreSQL/Definition/Procedure.hs
squeal-postgresql/src/Squeal/PostgreSQL/Manipulation/Call.hs
squeal-postgresql/src/Squeal/PostgreSQL/Type.hs
squeal-postgresql/src/Squeal/PostgreSQL/Type/PG.hs
squeal-postgresql/src/Squeal/PostgreSQL/Type/Schema.hs

This PR is best reviewed commit by commit.

More changes towards a new major version

---

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Array.hs

resolves #214

---

squeal-postgresql/src/Squeal/PostgreSQL/Session/Decode.hs
squeal-postgresql/src/Squeal/PostgreSQL/Session/Encode.hs

varchar/fixchar instances. tried to get some tests going but ran out of allotted time.

add varchar/fixchar support

---

squeal-postgresql/src/Squeal/PostgreSQL/Session/Migration.hs

having a field called `name` was way too clashy

migration data type names

---

squeal-postgresql/src/Squeal/PostgreSQL/Session/Decode.hs

Zip Row Decoders

---

squeal-postgresql/src/Squeal/PostgreSQL/Session/Result.hs
squeal-postgresql/test/Spec.hs

cmdStatus & cmdTuples functions
and export liftResult

cmdStatus & cmdTuples

---

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Range.hs

right range elem binop

---

squeal-postgresql/src/Squeal/PostgreSQL/Query/Table.hs
squeal-postgresql/src/Squeal/PostgreSQL/Session/Transaction.hs

Locking Clauses

---

squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/test/Property.hs

add roundtrip tests for enums

---

.github/workflows/ci.yml
squeal-postgresql-ltree/LICENSE
squeal-postgresql-ltree/README.md
squeal-postgresql-ltree/squeal-postgresql-ltree.cabal
squeal-postgresql-ltree/src/Squeal/PostgreSQL/LTree.hs
squeal-postgresql-uuid-ossp/LICENSE
squeal-postgresql-uuid-ossp/README.md
squeal-postgresql-uuid-ossp/squeal-postgresql-uuid-ossp.cabal
squeal-postgresql-uuid-ossp/src/Squeal/PostgreSQL/UUID/OSSP.hs
stack.yaml

Extra packages for ltree and uuid

Extra packages for ltree and uuid

---

squeal-postgresql/src/Squeal/PostgreSQL/Expression/Aggregate.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Window.hs

Overloaded label and qualified aggregate arguments

Overloaded label and qualified aggregate arguments

---

squeal-postgresql/src/Squeal/PostgreSQL/Session/Decode.hs

resolve #272

---

squeal-postgresql-ltree/src/Squeal/PostgreSQL/LTree.hs
squeal-postgresql/src/Squeal/PostgreSQL/Expression.hs

ltree and subset operator precedence

ltree and subset operator precedence

---

squeal-postgresql/src/Squeal/PostgreSQL/Session/Decode.hs
squeal-postgresql/src/Squeal/PostgreSQL/Session/Encode.hs
squeal-postgresql/src/Squeal/PostgreSQL/Session/Monad.hs
squeal-postgresql/src/Squeal/PostgreSQL/Session/Statement.hs
squeal-postgresql/test/Property.hs

Improve inference for generic parameter encoding and row decoding

Improve inference for generic parameter encoding and row decoding

---

.github/workflows/ci.yml

`actions/setup-haskell` has been archived: https://github.com/actions/setup-haskell

update Github Actions

---

squeal-postgresql-ltree/src/Squeal/PostgreSQL/LTree.hs
squeal-postgresql/src/Squeal/PostgreSQL/Session/Oid.hs

check for 0 results when doing OID lookups

better error messages

---

squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/src/Squeal/PostgreSQL/Session/Pool.hs

to `MonadIO` and `MonadCatch` from `MonadUnliftIO`.

generalize pools

---

squeal-postgresql-ltree/squeal-postgresql-ltree.cabal
squeal-postgresql/squeal-postgresql.cabal
squeal-postgresql/src/Squeal/PostgreSQL/Type/Schema.hs

version 0.9

---

RELEASE NOTES.md
squeal-postgresql/src/Squeal/PostgreSQL/Expression/Type.hs
squeal-postgresql/src/Squeal/PostgreSQL/Session/Oid.hs

also remove spaces bc newline obviates their need

release notes

---

squeal-postgresql/src/Squeal/PostgreSQL/Session.hs
squeal-postgresql/src/Squeal/PostgreSQL/Session/Oid.hs

I have bad internet connection now and can't compile locally so hopefully this works

fix doc tests hopefully

---

.github/workflows/ci.yml
README.md
squeal-postgresql/README.md
squeal-postgresql/squeal-postgresql.cabal
stack-ghc9_6.yaml
stack.yaml

ghc updates
